** 关于挤地铁的一点微小经验
   有听在北京工作过的同学形容过早上在回龙观挤地铁的景象，他这并没有直接说早高峰的地铁有多挤多挤，而是采取了从侧面描写的方法，下午坐地铁下车出站后，会看到外面围了一圈小区，这圈小区之外又围了另一圈小区。
   笔者近半年则在上海每天早上要做11号线，11号线终点站是嘉定，早上会有多少人来自不必形容，这批持续的人流量使得早晨的地铁车箱挤得就像是鱼肉罐头，车一到站还未停，便可见得里面已满了，但一开门间，总是有各乘客各显神通，总还是能再挤进去几个，不由得令人感叹上班着实辛苦。
   早上班，晚下班，11号线从未怎么空过，以下分享几条乘坐这种拥挤程度极高的地铁的一点微小经验，供各位一览而乐。
   1. 不要和提着行李箱的在一个车门等车。
   2. 不要和抱、带小孩子的在一个车门等车。
   3. 上车时若人不是很多，尽可能往两排座位之间的走道站定，之后人上得再多，这种走道位置却总是相对宽敞一些，靠近门口无座区域人的密度最高。
   4. 一条地铁很长，若是到了在门前也要排队程度，可以往贴有地铁站名的墙那里走，那里空间有限，排的队往往会短一些。
   5. 若一开门，车箱看上去已经满了，其实往往还是能上去的，主要看车箱地上有没有可以站住的位置，一旦有，先用脚站住，伸手扒住车门上沿将身体固定，等车门关上就好了。
   6. 有些站会下很多人，有些人在这些站又会很早就会担心自己下不去车，早早得就要开始往前挪，惹得大家受罪，这时往往跟他说自己也要下便可以止住这种无意义的折腾。
   7. 无扶手可扶时，面朝列车运行方向的侧面更容易保持平衡，若是面朝或背对基本会踉跄。
   8. 地铁上带普通塞耳式耳机经常会被列车的轰鸣盖掉，建议降噪耳机。

** 我为什么抛弃Things而全面转向疯狂番茄
   笔者在前阵子曾一度重度使用Things，颜值自然是好看的，然而投射到日常自身事务的推动以及对个人项目进程的掌握感却是效果差强人意。
   其原因大体在于两点：其一是重度使用后，会发现做一为一款GTD工具它显得有些不够用；其二则是无法监管自己分配到各任务上的时间而对有限的时间加以控制和反思。
   逛知乎时偶然发现了疯狂番茄这款软件，略加试用后，便选择将Things全面抛弃。这种毫不犹豫个中的思考如下。
   
*** 正确的软件做正确的事
    Things功能还是比较强大的，各种层级、标签的功能不可谓不好用，然而也正是由于这一点，很容易让人陷入一种误区，即，任何GTD上的事情都拿它来做。
    其实， *今日待办* 与 *项目拆解、跟踪规划、资料收集* 之间的差异还是比较大的，把这些事全放到Things里对它来说的确有点不堪重负，而只用Things来做今日待办又未免有点大材小用，而这也正是笔者抛弃Things的最重要的一个原因。
    
    改进后的方案为：
    使用番茄工作法做今日待办，理想情况是每天列今日待办时，应该是从空开始的。同时做今日待办的方式是：番茄工作法。
    项目拆解等一系列等复杂的事情则完全迁移到Trello上，这点是参考公司中做各种项目使用Jira这种看板类型的跟踪工具而决定做出的改变。
    此类工具有很多，还有Jira，Teambition等，一眼可以看到更多的事情，同时有推进感，添加附件、评论等功能也在项目推进过程中起着必不可少的作用。
    Trello作为个人管理工具真的是再合适不过了，免费且各平台平滑同步，而且可以从Unsplash上直接选择好看的看板背景来作为相应项目主题的激励与决心，十分推荐。

*** 今日待办与番茄计时的内聚性
    *今日待办与番茄计时应该是todolist软件应有的内聚性。* 这一点如此重要，却在使用疯狂番茄之前从未意识到。
    一直知道番茄工作法及其详细的工作机制与好处，却从未使用，其原因现在想来大体是由于还要在todolist之外再增加一个专门的用来进行番茄计时的软件，不知两者该如何一起工作，找不到切入点。
    使用疯狂番茄后突然就明白了， *番茄工作法应该是做todolist上每个task的具体操作方式。*
    现在依然能搜到很多介绍番茄工作法的文章是在使用omnifocus这样的软件，聚集到某task后，再打开另一款计时软件开始计时，这大幅增加了操作的繁琐程度。
    不同于上面那种不自然的分离，疯狂番茄很自然地将两者有机地结合到了一起，从预估时间及执行记录时间，从操作上讲便利了很多，更重要的是改进了笔者的GTD流程，将番茄工作法以一种很棒的方式引入了进来。
    
*** 预估时间及提醒
    之前处理Things上的任务时，有可能会在某个task上遇到困难，而选择正面刚，可能一下午就过去了，其他task自然没有被处理的机会，而从重要性上来讲，刚的这个task却不怎么重要。
    使用疯狂番茄，在写下今天要做这件事时，便为其预估时间，比如要研究这个软件两个番茄，若是其超出预料的复杂发现进展不理想，那么等到了两个番茄时也会收到提醒，这相当于一记警钟，会更容易停止这个坑而转向其他事情，这个task今日就到此为止。
    这之间很重要的一点区别是进行时间控制时的视角，每天早上刚到公司，开始规划今天要做什么，此时的视野是广阔的，不用深入任何一个task的细节问题，自然愿意为相对重要的事情投入更多，这完全不同于将时间控制延迟到做某一件事时才决定，后者往往会由于上头等因素做出不理智的判断与行为。
